apiVersion: v1

kind: Service

metadata:

  name: docker-kuber

spec:

  type: LoadBalancer

  selector:

    app: docker-kuber

  ports:

    - protocol: TCP

      port: 80

      targetPort: 8080

